server:
  port: 8089
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template-location: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/lunch?characterEncoding=UTF-8&serverTimezone=KST&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: P@ssw0rd
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 30
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100
logging:
  level:
    org:
      hibernate:
        sql: debug
        type: info
        query: info
#  datasource:
#    hikari:
#      jdbc-url: jdbc:mysql://localhost:3306/lunch?useSSL=false&characterEncoding=UTF-8&serverTimezone=KST
#      pool-name: hikari-cp
#      maximum-pool-size: 30
#      minimum-idle: 2
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: root
#      password: P@ssw0rd
